server:
  port: 8090

logging:
  level:
    org.springframework.ai: DEBUG
    reactor.core: TRACE


spring:
  cassandra:
    contact-points: 127.0.0.1:9042
    local-datacenter: datacenter1
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config.json
    openai:
      api-key: ${api.sk}
      base-url: ${api.uri}
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      base-url: http://localhost:11434
      chat:
        model: my-deepseek-R1-14b
      embedding:
        model: lrs33/bce-embedding-base_v1:latest
        options:
          model: lrs33/bce-embedding-base_v1:latest
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
          username: root
          password: Milvus
        databaseName: another_domain
        collectionName: vector_store
        embeddingDimension: 768
        indexType: IVF_FLAT
        metricType: COSINE
        initialize-schema: true
        auto-id: true
        id-field-name: doc_id
    chat:
      memory:
        cassandra:
          table: chat_history
          keyspace: another_domain_ai